--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/HotBox-PMMP/HotBox

branches:
- master

projects:
  HotBox:
    #projectId: 3361
    path: ""
    icon: assets/icon/512x512.png
...