---
name: HotBox
main: kim\present\hotbox\HotBox
version: 1.0.0-ALPHA
api: [3.0.0, 3.0.0-ALPHA12]
author: PresentKim
website: https://github.com/PresentKim/HotBox-PMMP
description: Have fun with the box for hot-time!

permissions:
  hotbox.cmd:
    description: HotBox command
    default: op
    children:
      hotbox.cmd.open:
        description: HotBox command - open
        default: true
      hotbox.cmd.edit:
        description: HotBox command - edit
        default: op
      hotbox.cmd.on:
        description: HotBox command - on
        default: op
      hotbox.cmd.off:
        description: HotBox command - off
        default: op
...