---
name: HotBox
main: kim\present\hotbox\HotBox
version: 1.4.1
api: [3.0.0, 3.0.0-ALPHA12, 4.0.0]
author: PresentKim
website: https://github.com/PresentKim/HotBox-PMMP
description: Have fun with the box for hot-time!

permissions:
  hotbox.cmd:
    description: HotBox command
    default: true
    children:
      hotbox.cmd.open:
        description: HotBox command - open
        default: true
      hotbox.cmd.edit:
        description: HotBox command - edit
        default: op
      hotbox.cmd.enable:
        description: HotBox command - enable
        default: op
      hotbox.cmd.disable:
        description: HotBox command - disable
        default: op
...