# Advanced configuration file for HotBox plugin
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading

settings:
  #Multi-language setting
  #Available: eng, kor
  language: "eng"

  #Form id for HotBox
  #It was determined by the HotBox repo ID (According to https://api.github.com/repos/PresentKim/HotBox-PMMP)
  formId: 1375577770 #137557777 + 0

command:
  #Name of main command
  #You can change this to be what you want
  name: "hotbox"

  #Aliases of main command
  #You can add, replace, or remove them as you like
  aliases: ["hb", "hottimebox"]

  children:
    #Setting of subcommands
    #Same as main command setting
    open:
      name: "Open"
      aliases: ["o"]
    edit:
      name: "Edit"
      aliases: ["e"]
    enable:
      name: "Enable"
      aliases: ["on", "start"]
    disable:
      name: "Disable"
      aliases: ["off", "stop"]